//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tooldietrainEntities : DbContext
    {
        public tooldietrainEntities()
            : base("name=tooldietrainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<td_comment> td_comment { get; set; }
        public DbSet<td_job_progress> td_job_progress { get; set; }
        public DbSet<tm_group> tm_group { get; set; }
        public DbSet<tm_job_cal> tm_job_cal { get; set; }
        public DbSet<tm_rack_mold> tm_rack_mold { get; set; }
        public DbSet<tm_rack_part> tm_rack_part { get; set; }
        public DbSet<tm_rack_process> tm_rack_process { get; set; }
        public DbSet<tm_user_id> tm_user_id { get; set; }
        public DbSet<tr_job_progress> tr_job_progress { get; set; }
        public DbSet<tr_main_job> tr_main_job { get; set; }
        public DbSet<tr_sub_job> tr_sub_job { get; set; }
        public DbSet<ts_process_result> ts_process_result { get; set; }
        public DbSet<tt_assy_stat> tt_assy_stat { get; set; }
        public DbSet<tt_date_time> tt_date_time { get; set; }
        public DbSet<tt_machine_stat> tt_machine_stat { get; set; }
        public DbSet<td_bite_status> td_bite_status { get; set; }
        public DbSet<tr_job_progress_log> tr_job_progress_log { get; set; }
        public DbSet<tr_process> tr_process { get; set; }
        public DbSet<td_user_skill> td_user_skill { get; set; }
        public DbSet<tr_machine> tr_machine { get; set; }
    }
}
