//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_job_progress
    {
        public string transaction_no { get; set; }
        public string main_job_no { get; set; }
        public string sub_job_no { get; set; }
        public Nullable<int> marking_step { get; set; }
        public string process_code { get; set; }
        public Nullable<int> qty { get; set; }
        public string machine_no { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string update_date { get; set; }
        public string update_time { get; set; }
        public string process_status { get; set; }
        public string start_date { get; set; }
        public string start_time { get; set; }
        public string start_user_id { get; set; }
        public string start_user_name { get; set; }
        public string finished_date { get; set; }
        public string finished_time { get; set; }
        public string finished_user_id { get; set; }
        public string finished_user_name { get; set; }
        public string transfer_sign { get; set; }
        public string status_auto_cal { get; set; }
        public string group_no { get; set; }
        public string type_est { get; set; }
    }
}
