//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_user_skill
    {
        public string user_id { get; set; }
        public bool evaluation { get; set; }
        public string proc_code { get; set; }
        public string skill_type { get; set; }
        public string update_date { get; set; }
    }
}
