//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_bt_version_ctrl
    {
        public string location_cd { get; set; }
        public string program_name { get; set; }
        public string bt_version { get; set; }
        public string upd_server { get; set; }
    }
}
