//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_cutoff_date
    {
        public string cutoff_date { get; set; }
        public string cutoff_time { get; set; }
        public string cutoff_userid { get; set; }
        public string cutoff_username { get; set; }
        public Nullable<int> sign { get; set; }
    }
}
