//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_group_type
    {
        public int object_id { get; set; }
        public Nullable<int> product_type_id { get; set; }
        public string product_type_code { get; set; }
        public string code { get; set; }
        public string name { get; set; }
    }
}
