//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_master_menu
    {
        public string admin_sign { get; set; }
        public string menu_no { get; set; }
        public string name_menu { get; set; }
    }
}
