//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_rack_part
    {
        public string transaction_no { get; set; }
        public string location_cd { get; set; }
        public string proc_code { get; set; }
        public string proc_name { get; set; }
        public string rack_no { get; set; }
        public string main_job_no { get; set; }
        public string sub_job_no { get; set; }
        public string item { get; set; }
        public string status_use { get; set; }
        public string update_date { get; set; }
        public string update_time { get; set; }
        public string update_user { get; set; }
    }
}
