//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_user_id
    {
        public string location_cd { get; set; }
        public string group_cd { get; set; }
        public string user_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string admin_sign { get; set; }
        public string pw { get; set; }
        public string entry_date { get; set; }
        public string rank { get; set; }
        public string full_name { get; set; }
    }
}
