//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_job_progress_log
    {
        public string main_job_no { get; set; }
        public string sub_job_no { get; set; }
        public int marking_step { get; set; }
        public string process_code { get; set; }
        public Nullable<int> qty { get; set; }
        public string machine_no { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string update_date { get; set; }
        public string update_time { get; set; }
        public string delete_date { get; set; }
        public string delete_time { get; set; }
    }
}
