//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_process
    {
        public string proc_code { get; set; }
        public string proc_name { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string update_date { get; set; }
        public string update_time { get; set; }
        public string standard_time { get; set; }
        public Nullable<int> skip_process_setup { get; set; }
        public string skill_type { get; set; }
        public int del_flag { get; set; }
    }
}
