//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_sub_job
    {
        public string main_job_no { get; set; }
        public string sub_job_no { get; set; }
        public Nullable<int> seq_no { get; set; }
        public string item_part_name { get; set; }
        public string description { get; set; }
        public Nullable<int> qty { get; set; }
        public string unit { get; set; }
        public string ref_sub_workorder { get; set; }
        public string wo_evaluation { get; set; }
        public string rank { get; set; }
        public Nullable<int> repair_qty { get; set; }
        public Nullable<int> repair_sub_job_oid { get; set; }
        public string remark { get; set; }
        public string cancel_date { get; set; }
        public string cancel_time { get; set; }
        public string cancel_by { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string update_date { get; set; }
        public string update_time { get; set; }
        public Nullable<int> group_type_id { get; set; }
        public string group_type_code { get; set; }
        public Nullable<int> type_id { get; set; }
        public string type_code { get; set; }
    }
}
