//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_machine_stat
    {
        public string process_code { get; set; }
        public string machine_no { get; set; }
        public string main_job_no { get; set; }
        public string sub_job_no { get; set; }
        public int marking_step { get; set; }
    }
}
